Adding a common before request rate limiter for RPS
hyperledger/firefly-common pull request #141
Opened 2024-05-30 09:39 UTC by Chengxuan

Adding `RPS` as a configuration so the ffresty client can submit requests at certain rates.

Note that this option is not optimal if other clients are using the REST endpoint under the same rate limit bucket.

To handle scenarios like that, we should update ffresty client to be Retry-after header aware or allow users to provide custom handling logic if they use different standards.

2024-05-31 08:53 UTC, EnriqueL8 requested changes

2024-05-31 08:53 UTC, EnriqueL8 commented on pkg/ffresty/config.go
> +	HTTPRPS = "rps"
Would prefer more explicit configuration name
```suggestion
	HTTPRPS = "maxRequestsPerSecond"
```

2024-05-31 08:53 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	var rpsLimiter *rate.Limiter
There is a native rate limiter that can be associated with the resty client https://github.com/go-resty/resty/pull/715/files so we wouldn''t need to call Wait ourselves. I think this is neater

2024-05-31 08:53 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	var rpsLimiter *rate.Limiter
Would look like 
```
client.SetRateLimiter(rate.NewLimiter(rate.Limit(rps), rps)
```

2024-05-31 09:12 UTC, Chengxuan commented on pkg/ffresty/ffresty.go
> +	var rpsLimiter *rate.Limiter
the resty rate limit fails the request if the rate exceeded the limit while the behaviour introduced in this PR use the native golang rate limiter to wait.

2024-05-31 09:19 UTC, Chengxuan commented on pkg/ffresty/config.go
> +	HTTPRPS = "rps"
Is it because it's too short, or developers using ffresty wouldn't understand what RPS is (like they would do for URL/TLS)?  `rps` is a common attribute for most ingress configurations, that's the reason i keep it consistent.

2024-05-31 09:19 UTC, Chengxuan commented
@EnriqueL8 thanks for the review. Replied to your comments

2024-05-31 10:03 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	var rpsLimiter *rate.Limiter
ah I see - so it's like a buffer, we wait a max of a second until the next requests go through

2024-05-31 10:03 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	var rpsLimiter *rate.Limiter
Chatted that the context used should be the request context

2024-06-06 13:25 UTC, peterbroadhurst commented on pkg/ffresty/ffresty.go
> +		rateLimiter = rate.NewLimiter(rate.Limit(ffrestyConfig.RequestPerSecond), ffrestyConfig.RequestPerSecond)
I think related to above comment `r` and `b` here should be separate configurations, with separate defaults

2024-06-06 13:26 UTC, peterbroadhurst requested changes
Really great that there's a leaky bucket algorithm built into Go to plug in here 🎉 

One request on the configuration split.

2024-06-06 13:55 UTC, Chengxuan commented
@peterbroadhurst comments addressed

2024-06-07 17:07 UTC, peterbroadhurst approved these changes
Thanks @Chengxuan for the extra spelling round there - looks great

2024-06-07 17:08 UTC, merged