ffresty metrics and hooks
hyperledger/firefly-common pull request #143
Opened 2024-06-04 12:25 UTC by alexwood

2024-06-04 14:07 UTC, onelapahead reviewed
Overall approved, just a few small points. Ty for the great unit test!

2024-06-04 14:07 UTC, onelapahead commented on pkg/ffresty/ffresty.go
> +	onErrorHooks []func(*resty.Request, error)
This looks great to me, think we want to make some comments indicating we do not protect these lists with mutex's bc we only expect `Register` funcs to be called on startup.

nit: lets make a types for these funcs? i.e.`type ErrorProcessor func(*resty.Request, error)` ?

2024-06-04 14:07 UTC, onelapahead commented on pkg/ffresty/ffresty.go
> +	mm, err := metricsRegistry.NewMetricsManagerForSubsystem(ctx, "ffresty")
I think by default all metrics made through our lib get prefixed with `ff` so maybe this subsystem can just be called `resty` ?

Otherwise think its fine that the resty clients have a dedicated manager, and then users just need to provide a registry which is presumably wired up to their metrics server to expose the client metrics.

2024-06-04 14:07 UTC, onelapahead commented on pkg/ffresty/ffresty.go
> +	metricsManager.NewCounterMetricWithLabels(ctx, "http_response", "HTTP response", []string{"status","error"}, false)
I know I said in the issue that a `url` tag might be too high in cardinality, but what about a `host` tag ?

That should be lower in cardinality since it won't include all the paths permutations, but very helpful for determining if HTTP / TCP errors are for particular hosts / backends or not.

2024-06-04 16:36 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +	onErrorHooks []func(*resty.Request, error)
used the built in one from resty itself

2024-06-04 16:36 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +	mm, err := metricsRegistry.NewMetricsManagerForSubsystem(ctx, "ffresty")
changed removed the ff

2024-06-04 16:38 UTC, alexwood commented
So playing with dashboards and not seeing the status code for errors :( they come out with status code `0`  not sure why will have to add some trace logging to figure it out.

I think what I really want is to see the 500/502/503 etc coming out here.

2024-06-05 08:44 UTC, alexwood commented
More improvements as discussed - tested in an apigw application that calls multiple hosts  and can see useful metrics for both response codes and response time coming out

<img width="1643" alt="Screenshot 2024-06-05 at 09 43 44" src="https://github.com/hyperledger/firefly-common/assets/3380252/a6774d16-1325-4424-948d-dcc6803af2e2">

2024-06-05 10:35 UTC, EnriqueL8 reviewed
Mainly around if this should be config option and not having a "global" enable metrics manager. I get that you need to pass in the manager to it and we return a resty.Client not a ffresty interface that we could extend to enable metrics


Update missed the issue comment, it sounds like we want to have it global for adding hooks https://github.com/hyperledger/firefly-common/issues/142#issuecomment-2140071723 and since we do not have a FFResty object we need to use these package vars to store them

2024-06-05 10:35 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +)
This feels like an anti pattern in Golang storing into vars as this will be for the whole package? Shouldn't these be nested under the client?

2024-06-05 10:35 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +)
And I think it should be driven through the config to instantiate one per client?

2024-06-05 10:35 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	client.OnSuccess(func(c *resty.Client, r *resty.Response) { OnSuccess(c, r) })
I wonder if this should be a flag to enable metrics on the config as users might override this afterwards if they wish?

2024-06-05 10:39 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +	client.OnSuccess(func(c *resty.Client, r *resty.Response) { OnSuccess(c, r) })
This needs to be always be here by default to enable adding hooks that apply to previously created clients, so all good

2024-06-05 11:55 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +)
this was part of the intention of this change that this is globally statically configured not per instance

2024-06-05 11:55 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +)
see https://github.com/hyperledger/firefly-common/issues/142 for explanation

2024-06-05 14:07 UTC, onelapahead commented on pkg/ffresty/ffresty.go
> +	metricsManager.NewGaugeMetricWithLabels(ctx, "http_duration", "HTTP duration", []string{"status", "error", "host", "method"}, false)
So `duration` would be best as a Histogram with a few buckets as opposed to a guage.

From there, we can calculate average response time and estimate percentiles if we want but it is high cardinality, and the buckets is likely something we'd want to expose as config on this method or globally.

2024-06-05 15:07 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +	metricsManager.NewGaugeMetricWithLabels(ctx, "http_duration", "HTTP duration", []string{"status", "error", "host", "method"}, false)
removed the gauge metric

2024-06-05 15:09 UTC, onelapahead reviewed
looks good! ty

2024-06-05 15:31 UTC, EnriqueL8 approved these changes
LGTM

2024-06-05 16:19 UTC, peterbroadhurst requested changes
This contribution looks great @alexwood 
I like that you've taken the `RegisterGlobal...` approach, but also provided a pre-baked example for metrics that can be used by a consumer of this library that is buying into the metrics stack that's also in `firefly-common`.

That aligns really well with the spirit of the utilities in this package.

The only request before merge from me is that to keep the coverage up on the repo, as we've found it helpful to keep a 100% coverage on these utilities.

2024-06-05 16:19 UTC, peterbroadhurst commented on pkg/ffresty/ffresty.go
> +		return err
UT test gap on this line

2024-06-05 16:19 UTC, peterbroadhurst commented on pkg/ffresty/ffresty.go
> +				metricsManager.IncCounterMetricWithLabels(ctx, "http_response", map[string]string{"status": fmt.Sprintf("%d", code), "error": "true", "host": host, "method": method}, nil)
UT test gap on this line

2024-06-06 10:52 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +		return err
additional tests added

2024-06-06 10:56 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +				metricsManager.IncCounterMetricWithLabels(ctx, "http_response", map[string]string{"status": fmt.Sprintf("%d", code), "error": "true", "host": host, "method": method}, nil)
so this proved impossible to mock since net/http deliberately nils the response if the error is set. 
reading the net/http code their was a fringe case where it did allow it through and I was able to hit this in full stack testing, but in such case the statusCode was `0` so not useful
Therefore I decided for OnError to now log http_response metric and only log the network_error metric.

2024-06-06 10:56 UTC, alexwood commented on pkg/ffresty/ffresty.go
> +				metricsManager.IncCounterMetricWithLabels(ctx, "http_response", map[string]string{"status": fmt.Sprintf("%d", code), "error": "true", "host": host, "method": method}, nil)
updated now coverage should be 100%

2024-06-06 13:00 UTC, alexwood commented
@peterbroadhurst  this is ready for re-review - thanks

2024-06-06 13:17 UTC, peterbroadhurst approved these changes

2024-06-06 13:17 UTC, merged