feat: Add mTLS configuration for ffresty
hyperledger/firefly-common pull request #65
Opened 2023-04-19 10:03 UTC by EnriqueL8

Adding the ability to supply a config to the ffresty client to setup TLS and mTLS.

**NOTE** This changes the interface of that init function to now return an error as well, so every consumer of this library and that client on update will need to handle that error. We could avoid doing this by allowing the user to provide a TLS Config as an argument but the pattern seems to be to provide viper config!

For testing I added a series of real and fake certificates and keys. I also explore standing up an mTLS mock server with the `httptest` but it proved cumbersome. I think validating that the correct certificates are added to the TLS Config should be good enough but happy to rectify

2023-04-19 19:55 UTC, peterbroadhurst requested changes
This is great @EnriqueL8 - A few suggestions/questions to consider.

2023-04-19 19:55 UTC, peterbroadhurst commented on test/certs/ca-crt.pem
Would be good to be consistent with this code - in fact to re-use that code.

The problem with checking in certs, is that they expire over time. So generating them is much preferred

https://github.com/hyperledger/firefly-common/blob/f43b8dafc0dcd153ffaaac6c0b44b0ad1ead55ef/pkg/httpserver/httpserver_test.go#L139-L163

2023-04-19 19:55 UTC, peterbroadhurst commented on pkg/ffresty/ffresty.go
> +			tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}
Related to the other comments on checking in test files, would be good to consider if we can avoid duplication of all this code (and maybe even the config structure) with https://github.com/hyperledger/firefly-common/blob/f43b8dafc0dcd153ffaaac6c0b44b0ad1ead55ef/pkg/httpserver/httpserver.go#L111-L126

2023-04-19 19:55 UTC, peterbroadhurst commented on pkg/ffresty/ffresty.go
> +func New(ctx context.Context, staticConfig config.Section) (client *resty.Client, err error) {
As you mention, this line will drive a lot of change in the components.

I wonder if the right answer here, is to prepare a set of PRs against the other `hyperledger/firefly-*` repositories - otherwise they would become unable to pick up security maintenance.

2023-04-19 21:47 UTC, EnriqueL8 commented on test/certs/ca-crt.pem
Makes sense - will rework that!

2023-04-19 21:47 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +			tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}
Agreed - maybe a tls sub directory with it's own config

2023-04-19 21:48 UTC, EnriqueL8 commented on pkg/ffresty/ffresty.go
> +func New(ctx context.Context, staticConfig config.Section) (client *resty.Client, err error) {
Sounds like a plan, have already started on the main firefly but will look at the other repos and coordinate the changes

2023-04-21 14:59 UTC, EnriqueL8 commented on pkg/ffresty/config.go
> +	fftls.InitTLSConfig(tlsConfig)
I wonder if this is the best way to do it - having problem with existing plugins in firefly to refactor the InitConfig

2023-04-24 15:17 UTC, EnriqueL8 commented on pkg/ffresty/config.go
> +	fftls.InitTLSConfig(tlsConfig)
Resolve it to be a deprecated config we can remove

2023-04-25 18:33 UTC, peterbroadhurst approved these changes
Awesome. Thanks for going the extra mile to package this one all up so tidily @EnriqueL8!

2023-04-25 18:34 UTC, merged